### ISSUE TITLE
How did you preprocess the Mimic Reports.

### ISSUE THREAD

**Issue by astammer** [wang-zhanyu/R2GenGPT#8]
Hello, 

I was wondering how exactly you preprocessed the Mimic-CXR Reports. 
As you stated in your paper, you partitioned the data by the official split of Mimic-CXR, which resulted in 270790 samples designated for training, while allocating 2130 and 3,858 samples for validation and testing. I can not find an indication of any other kind of preprocessing. But the official split yields the following numbers of images/samples  368,960 (Train) 2,991(Validate) 5,159(Test). 
Could you please explain, why your annotations have less data and how it was determined?

Thank you!

**Comment by wang-zhanyu** [comment]
Thanks for your interest. We adopt the same data partitioning as [R2Gen](https://arxiv.org/pdf/2010.16056.pdf), since many works have utilized their data. Then, we referred to the [official code ](https://github.com/MIT-LCP/mimic-cxr) provided to preprocess the report.

**Comment by astammer** [comment]
Thank you very much! 

Maybe I am overseeing something, but here are the sample numbers stated by R2Gen, which correspond to the official split, but differ from your annotations. 

<img width="474" alt="image" src="https://github.com/wang-zhanyu/R2GenGPT/assets/73904678/1a11740c-d5b9-493f-b8db-665e23753f28">

I apologize, if I am overseeing something obvious.

**Comment by astammer** [comment]
My question is resolved. For anyone who is also confused by the sample sizes, please refer to:  https://github.com/zhjohnchan/R2Gen/issues/1
